# Operations
SHUTDOWN        = chr(1)
CONNECT         = chr(2)
DB_OPEN         = chr(3)
DB_CREATE       = chr(4)
DB_CLOSE        = chr(5)
DB_EXIST        = chr(6)
DB_DROP         = chr(7)
DB_SIZE         = chr(8)
DB_COUNTRECORDS = chr(9)
DB_RELOAD       = chr(73)
